-- Módulo de orçamentos e automações de envio, 7 dias e 14 dias.
-- Migration aditiva, sem backfill e sem criação retroativa de mensagens.

BEGIN;

CREATE TABLE public.orcamentos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    cliente_id UUID NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
    veiculo_id UUID REFERENCES public.veiculos(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'rascunho',
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    desconto NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    validade DATE NOT NULL,
    observacoes TEXT NOT NULL DEFAULT '',
    sent_at TIMESTAMPTZ,
    created_by UUID DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT orcamentos_status_check CHECK (
        status IN ('rascunho', 'enviado', 'aceito', 'recusado', 'cancelado', 'vencido', 'convertido')
    ),
    CONSTRAINT orcamentos_values_check CHECK (
        subtotal >= 0 AND desconto >= 0 AND desconto <= subtotal AND total = subtotal - desconto
    ),
    CONSTRAINT orcamentos_send_check CHECK (
        (status = 'rascunho' AND sent_at IS NULL) OR (status <> 'rascunho' AND sent_at IS NOT NULL)
    ),
    CONSTRAINT orcamentos_notes_check CHECK (length(observacoes) <= 4000)
);

CREATE TABLE public.orcamento_itens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    orcamento_id UUID NOT NULL REFERENCES public.orcamentos(id) ON DELETE CASCADE,
    servico_id UUID REFERENCES public.servicos_disponiveis(id) ON DELETE SET NULL,
    descricao TEXT NOT NULL,
    quantidade NUMERIC(10,2) NOT NULL,
    valor_unitario NUMERIC(12,2) NOT NULL,
    total NUMERIC(12,2) GENERATED ALWAYS AS (round(quantidade * valor_unitario, 2)) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT orcamento_itens_values_check CHECK (
        length(btrim(descricao)) BETWEEN 1 AND 500 AND quantidade > 0 AND valor_unitario >= 0
    )
);

CREATE INDEX idx_orcamentos_cliente_created
    ON public.orcamentos (cliente_id, created_at DESC);
CREATE INDEX idx_orcamentos_status_validade
    ON public.orcamentos (status, validade);
CREATE INDEX idx_orcamento_itens_orcamento
    ON public.orcamento_itens (orcamento_id);

ALTER TABLE public.orcamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orcamento_itens ENABLE ROW LEVEL SECURITY;

CREATE POLICY orcamentos_staff_all
ON public.orcamentos
FOR ALL TO authenticated
USING (public.portal_is_active_staff())
WITH CHECK (public.portal_is_active_staff());

CREATE POLICY orcamento_itens_staff_all
ON public.orcamento_itens
FOR ALL TO authenticated
USING (public.portal_is_active_staff())
WITH CHECK (public.portal_is_active_staff());

REVOKE ALL ON TABLE public.orcamentos, public.orcamento_itens FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.orcamentos, public.orcamento_itens
TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.orcamentos_numero_seq
TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.fn_proteger_orcamento()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'rascunho' THEN
            RAISE EXCEPTION 'Somente orçamentos em rascunho podem ser excluídos';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.status <> 'rascunho' AND (
        NEW.cliente_id IS DISTINCT FROM OLD.cliente_id
        OR (
            NEW.veiculo_id IS DISTINCT FROM OLD.veiculo_id
            AND NOT (OLD.veiculo_id IS NOT NULL AND NEW.veiculo_id IS NULL)
        )
        OR NEW.subtotal IS DISTINCT FROM OLD.subtotal
        OR NEW.desconto IS DISTINCT FROM OLD.desconto
        OR NEW.total IS DISTINCT FROM OLD.total
        OR NEW.validade IS DISTINCT FROM OLD.validade
        OR NEW.observacoes IS DISTINCT FROM OLD.observacoes
    ) THEN
        RAISE EXCEPTION 'O conteúdo de um orçamento enviado é imutável';
    END IF;
    IF OLD.status <> 'rascunho' AND NEW.status IN ('rascunho', 'enviado') THEN
        RAISE EXCEPTION 'Um orçamento enviado não pode voltar ao estado inicial';
    END IF;
    IF OLD.status NOT IN ('rascunho', 'enviado') AND NEW.status <> OLD.status THEN
        RAISE EXCEPTION 'Um orçamento encerrado não pode mudar de estado';
    END IF;

    IF OLD.status = 'rascunho' AND NEW.status = 'enviado' THEN
        NEW.sent_at := coalesce(NEW.sent_at, now());
    ELSIF NEW.status = 'rascunho' THEN
        NEW.sent_at := NULL;
    ELSE
        NEW.sent_at := coalesce(NEW.sent_at, OLD.sent_at);
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_proteger_orcamento_update
BEFORE UPDATE ON public.orcamentos
FOR EACH ROW EXECUTE FUNCTION public.fn_proteger_orcamento();

CREATE TRIGGER trigger_proteger_orcamento_delete
BEFORE DELETE ON public.orcamentos
FOR EACH ROW EXECUTE FUNCTION public.fn_proteger_orcamento();

CREATE OR REPLACE FUNCTION public.fn_proteger_item_orcamento()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
    v_orcamento_id UUID := CASE WHEN TG_OP = 'DELETE' THEN OLD.orcamento_id ELSE NEW.orcamento_id END;
    v_status TEXT;
BEGIN
    SELECT status INTO v_status FROM public.orcamentos WHERE id = v_orcamento_id;
    IF v_status <> 'rascunho' THEN
        IF TG_OP <> 'UPDATE'
           OR NEW.orcamento_id IS DISTINCT FROM OLD.orcamento_id
           OR NEW.descricao IS DISTINCT FROM OLD.descricao
           OR NEW.quantidade IS DISTINCT FROM OLD.quantidade
           OR NEW.valor_unitario IS DISTINCT FROM OLD.valor_unitario THEN
            RAISE EXCEPTION 'Os itens de um orçamento enviado são imutáveis';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_proteger_item_orcamento
BEFORE INSERT OR UPDATE OR DELETE ON public.orcamento_itens
FOR EACH ROW EXECUTE FUNCTION public.fn_proteger_item_orcamento();

CREATE OR REPLACE FUNCTION public.fn_salvar_orcamento(
    p_orcamento_id UUID,
    p_cliente_id UUID,
    p_veiculo_id UUID,
    p_desconto NUMERIC,
    p_validade DATE,
    p_observacoes TEXT,
    p_itens JSONB
)
RETURNS UUID
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
    v_id UUID := coalesce(p_orcamento_id, gen_random_uuid());
    v_status TEXT;
    v_subtotal NUMERIC(12,2);
    v_item JSONB;
BEGIN
    IF jsonb_typeof(p_itens) <> 'array'
       OR jsonb_array_length(p_itens) NOT BETWEEN 1 AND 50 THEN
        RAISE EXCEPTION 'O orçamento deve possuir entre 1 e 50 itens';
    END IF;
    IF p_validade < current_date THEN
        RAISE EXCEPTION 'A validade do orçamento não pode estar no passado';
    END IF;
    IF p_veiculo_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.veiculos
        WHERE id = p_veiculo_id AND cliente_id = p_cliente_id
    ) THEN
        RAISE EXCEPTION 'O veículo não pertence ao cliente informado';
    END IF;

    SELECT round(sum(
        (item->>'quantity')::numeric * (item->>'unitPrice')::numeric
    ), 2)
    INTO v_subtotal
    FROM jsonb_array_elements(p_itens) AS item;

    IF v_subtotal IS NULL OR v_subtotal < 0
       OR coalesce(p_desconto, 0) < 0
       OR coalesce(p_desconto, 0) > v_subtotal THEN
        RAISE EXCEPTION 'Valores inválidos no orçamento';
    END IF;

    SELECT status INTO v_status FROM public.orcamentos WHERE id = v_id FOR UPDATE;
    IF FOUND AND v_status <> 'rascunho' THEN
        RAISE EXCEPTION 'Somente orçamentos em rascunho podem ser editados';
    END IF;

    INSERT INTO public.orcamentos (
        id, cliente_id, veiculo_id, status, subtotal, desconto, total,
        validade, observacoes
    ) VALUES (
        v_id, p_cliente_id, p_veiculo_id, 'rascunho', v_subtotal,
        coalesce(p_desconto, 0), v_subtotal - coalesce(p_desconto, 0),
        p_validade, coalesce(p_observacoes, '')
    )
    ON CONFLICT (id) DO UPDATE SET
        cliente_id = EXCLUDED.cliente_id,
        veiculo_id = EXCLUDED.veiculo_id,
        subtotal = EXCLUDED.subtotal,
        desconto = EXCLUDED.desconto,
        total = EXCLUDED.total,
        validade = EXCLUDED.validade,
        observacoes = EXCLUDED.observacoes;

    DELETE FROM public.orcamento_itens WHERE orcamento_id = v_id;
    FOR v_item IN SELECT value FROM jsonb_array_elements(p_itens)
    LOOP
        INSERT INTO public.orcamento_itens (
            orcamento_id, servico_id, descricao, quantidade, valor_unitario
        ) VALUES (
            v_id,
            nullif(v_item->>'serviceId', '')::uuid,
            btrim(v_item->>'description'),
            (v_item->>'quantity')::numeric,
            (v_item->>'unitPrice')::numeric
        );
    END LOOP;
    RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.fn_salvar_orcamento(UUID, UUID, UUID, NUMERIC, DATE, TEXT, JSONB)
FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_salvar_orcamento(UUID, UUID, UUID, NUMERIC, DATE, TEXT, JSONB)
TO authenticated, service_role;

ALTER TABLE public.automacoes_eventos
    ADD COLUMN orcamento_id UUID REFERENCES public.orcamentos(id) ON DELETE SET NULL;
ALTER TABLE public.automacoes_execucoes
    ADD COLUMN orcamento_id UUID REFERENCES public.orcamentos(id) ON DELETE SET NULL;
CREATE INDEX idx_automacoes_eventos_orcamento
    ON public.automacoes_eventos (orcamento_id);
CREATE INDEX idx_automacoes_execucoes_orcamento
    ON public.automacoes_execucoes (orcamento_id);

CREATE OR REPLACE FUNCTION public.fn_registrar_evento_orcamento(
    p_automacao TEXT,
    p_customer_id UUID,
    p_orcamento_id UUID,
    p_deduplication_key TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_is_active BOOLEAN;
    v_automations JSONB;
BEGIN
    IF p_automacao <> 'orcamento_enviado' THEN
        RAISE EXCEPTION 'Evento de orçamento inválido: %', p_automacao;
    END IF;

    SELECT CASE WHEN jsonb_typeof(config.automations) = 'array'
        THEN config.automations ELSE '[]'::jsonb END
    INTO v_automations
    FROM public.configuracoes_empresa AS config
    WHERE config.id = 'c0000000-0000-0000-0000-000000000000'::uuid;
    v_automations := coalesce(v_automations, '[]'::jsonb);

    IF jsonb_array_length(v_automations) = 0 THEN
        v_is_active := TRUE;
    ELSE
        SELECT EXISTS (
            SELECT 1 FROM jsonb_array_elements(v_automations) AS item
            WHERE item->>'event' = p_automacao
              AND item->'isActive' = 'true'::jsonb
              AND length(trim(coalesce(item->>'template', ''))) > 0
        ) INTO v_is_active;
    END IF;
    IF NOT v_is_active THEN RETURN; END IF;

    INSERT INTO public.automacoes_eventos (
        automacao, appointment_id, customer_id, orcamento_id, deduplication_key
    ) VALUES (
        p_automacao, NULL, p_customer_id, p_orcamento_id, p_deduplication_key
    ) ON CONFLICT (deduplication_key) DO NOTHING;
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'Falha isolada ao registrar evento de orçamento %: %',
        p_automacao, SQLERRM;
    RETURN;
END;
$$;

REVOKE ALL ON FUNCTION public.fn_registrar_evento_orcamento(TEXT, UUID, UUID, TEXT)
FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.fn_trigger_orcamento_enviado()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF OLD.status = 'rascunho' AND NEW.status = 'enviado' THEN
        PERFORM public.fn_registrar_evento_orcamento(
            'orcamento_enviado', NEW.cliente_id, NEW.id,
            'orcamento_enviado:' || NEW.id
        );
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_orcamento_enviado
AFTER UPDATE OF status ON public.orcamentos
FOR EACH ROW EXECUTE FUNCTION public.fn_trigger_orcamento_enviado();

CREATE OR REPLACE FUNCTION public.fn_enviar_orcamento(p_orcamento_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
    v_customer_id UUID;
    v_automations JSONB;
    v_is_active BOOLEAN;
BEGIN
    SELECT CASE WHEN jsonb_typeof(config.automations) = 'array'
        THEN config.automations ELSE '[]'::jsonb END
    INTO v_automations
    FROM public.configuracoes_empresa AS config
    WHERE config.id = 'c0000000-0000-0000-0000-000000000000'::uuid;
    v_automations := coalesce(v_automations, '[]'::jsonb);
    IF jsonb_array_length(v_automations) = 0 THEN
        v_is_active := TRUE;
    ELSE
        SELECT EXISTS (
            SELECT 1 FROM jsonb_array_elements(v_automations) AS item
            WHERE item->>'event' = 'orcamento_enviado'
              AND item->'isActive' = 'true'::jsonb
              AND length(trim(coalesce(item->>'template', ''))) > 0
        ) INTO v_is_active;
    END IF;
    IF NOT v_is_active THEN
        RAISE EXCEPTION 'A automação de envio de orçamento está desativada ou sem template';
    END IF;

    UPDATE public.orcamentos
    SET status = 'enviado'
    WHERE id = p_orcamento_id AND status = 'rascunho'
    RETURNING cliente_id INTO v_customer_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'O orçamento não está disponível para envio';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.automacoes_eventos
        WHERE deduplication_key = 'orcamento_enviado:' || p_orcamento_id
          AND orcamento_id = p_orcamento_id
          AND customer_id = v_customer_id
    ) THEN
        RAISE EXCEPTION 'O evento de envio não foi confirmado no outbox';
    END IF;
    RETURN p_orcamento_id;
END;
$$;

REVOKE ALL ON FUNCTION public.fn_enviar_orcamento(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_enviar_orcamento(UUID) TO authenticated, service_role;

WITH defaults(item, position) AS (
    VALUES
        (jsonb_build_object(
            'id', 'at_orcamento_enviado',
            'name', 'Envio de Orçamento',
            'description', 'Envia o orçamento quando o profissional confirma o envio.',
            'event', 'orcamento_enviado',
            'isActive', true,
            'template', E'Olá, *{nome}*! Segue o orçamento *#{orcamento_numero}*:\n\n{orcamento_itens}\n\n*Total:* R$ {orcamento_total}\n*Válido até:* {orcamento_validade}'
        ), 1),
        (jsonb_build_object(
            'id', 'at_orcamento_followup_7d',
            'name', 'Acompanhamento de Orçamento — 7 dias',
            'description', 'Retoma automaticamente um orçamento pendente após 7 dias.',
            'event', 'orcamento_followup_7d',
            'isActive', true,
            'template', 'Olá, *{nome}*! Gostaria de saber se deseja aprovar o orçamento *#{orcamento_numero}*, no valor de R$ {orcamento_total}, e agendar o serviço.'
        ), 2),
        (jsonb_build_object(
            'id', 'at_orcamento_followup_14d',
            'name', 'Acompanhamento de Orçamento — 14 dias',
            'description', 'Faz o segundo contato automático de um orçamento pendente após 14 dias.',
            'event', 'orcamento_followup_14d',
            'isActive', true,
            'template', 'Olá, *{nome}*! Este é um novo contato sobre o orçamento *#{orcamento_numero}*, no valor de R$ {orcamento_total}. Deseja aprovar e agendar o serviço?'
        ), 3)
), missing AS (
    SELECT defaults.item, defaults.position
    FROM defaults
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.configuracoes_empresa AS config,
             jsonb_array_elements(CASE WHEN jsonb_typeof(config.automations) = 'array'
                 THEN config.automations ELSE '[]'::jsonb END) AS existing(item)
        WHERE config.id = 'c0000000-0000-0000-0000-000000000000'::uuid
          AND existing.item->>'event' = defaults.item->>'event'
    )
), missing_array AS (
    SELECT coalesce(jsonb_agg(item ORDER BY position), '[]'::jsonb) AS items FROM missing
)
UPDATE public.configuracoes_empresa AS config
SET automations = (CASE WHEN jsonb_typeof(config.automations) = 'array'
        THEN config.automations ELSE '[]'::jsonb END) || missing_array.items,
    updated_at = now()
FROM missing_array
WHERE config.id = 'c0000000-0000-0000-0000-000000000000'::uuid
  AND jsonb_array_length(missing_array.items) > 0;

UPDATE public.usuarios AS usuario
SET permissions = coalesce(usuario.permissions, '{}'::jsonb) || jsonb_build_object(
    'orcamentos', CASE usuario.perfil
        WHEN 'admin' THEN '{"view":true,"create":true,"edit":true,"delete":true}'::jsonb
        WHEN 'gerente' THEN '{"view":true,"create":true,"edit":true,"delete":true}'::jsonb
        WHEN 'atendente' THEN '{"view":true,"create":true,"edit":true,"delete":false}'::jsonb
        WHEN 'tecnico' THEN '{"view":true,"create":false,"edit":false,"delete":false}'::jsonb
        ELSE '{"view":false,"create":false,"edit":false,"delete":false}'::jsonb
    END
)
WHERE NOT coalesce(usuario.permissions, '{}'::jsonb) ? 'orcamentos';

COMMIT;
